version: "2.1"
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt update
      - run: apt install -y curl
      - run: curl https://get.okteto.com -sSfL | sh
      - run: okteto
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
workflows:
  build_and_test:
    jobs:
      - build
      - test
