jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
workflows:
  version: "2.1"
  build_and_test:
    jobs:
      - build
      - test
