name: Cron Job for jenkins server

on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy jenkins
      - run: echo Install okteto
      - run: curl https://get.okteto.com -sSfL | sh
      - run: okteto --help
