name: Cron Job for jenkins server

on:
  schedule:
   - cron: "*/1 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
