name: Cron Job for jenkins server

on:
  schedule:
   - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
      - run: echo "This step will always run"
      - run: echo "This is step 2"
